iKnow/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('idunno/', include('idunno.urls')),
    path('', include('idunno.urls')),
    path('admin/', admin.site.urls),
]

idunno/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_question', views.add_question, name='add_question'),
    path('list/<str:sort_attr>', views.list, name='list'),
    path('game/<str:query>',views.game, name='game'),
    path('<int:question_id>/', views.question, name='question'),
    path('<int:question_id>/edit', views.edit_question, name='edit'),
    path('search/<str:query>', views.search, name='search')
]

idunno/models.py
from django.db import models
from django import forms
import random

COLORS = [
        ('B', 'Blue'),
        ('G', 'Green'),
        ('R', 'Red'),
        ('Y', 'Yellow')
    ]

class Question(models.Model):
    COLORS = {
        'B':'#009ce5',
        'G':'#33ac2d',
        'R':'#e50c07',
        'Y':'#fdc500',
    }

    question = models.TextField()
    hint3 = models.TextField()
    hint2 = models.TextField()
    hint1 = models.TextField()
    answer = models.TextField()
    color = models.CharField(
        max_length=10,
        choices=[
            ('B', 'Blue'),
            ('G', 'Green'),
            ('R', 'Red'),
            ('Y', 'Yellow')
        ]
    )
    @staticmethod
    def get_random_question(color=None):
        if color is None:
            color = COLORS[random.randint(0,3)][0]
        qs = Question.objects.all().filter(color=color)
        return qs[random.randint(0,len(qs)-1)]

idunno/forms.py
from django import forms
from .models import Question

class NewQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question','hint3','hint2','hint1','answer','color')

idunno/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Q
from django.shortcuts import redirect
from django.http import JsonResponse
from django.template.loader import render_to_string

from idunno.models import Question
from idunno.forms import NewQuestionForm

import json


def index(request):
    question = Question.get_random_question()

    context = {
        'index': True,
        'id': question.pk,
        'question': question.question,
        'hint3': question.hint3,
        'hint2': question.hint2,
        'hint1': question.hint1,
        'answer': question.answer,
        'color': Question.COLORS[question.color]
    }
    return render(request, 'idunno/index.html', context)


def add_question(request):
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            new_question = form.save(commit=True)
            new_question.save()
            return redirect('index')

    else:
        form = NewQuestionForm()
    return render(request, 'idunno/newQuestion.html', {'form': form})


def list(request, sort_attr='id'):
    questions = Question.objects.all().order_by(sort_attr)
    context = {'questions': questions}
    return render(request, "idunno/list.html", context)


def edit_question(request, question_id):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            question = Question.objects.get(pk=question_id)
            question.color = data['color']
            question.question = data['question']
            question.hint3 = data['hint3']
            question.hint2 = data['hint2']
            question.hint1 = data['hint1']
            question.answer = data['answer']
            print(question)
            question.save()
        except Exception:
            return HttpResponse(json.dumps({'succes': False}))

        return HttpResponse(json.dumps({'success': True}))
    else:
        question = Question.objects.get(pk=question_id)
        context = {
            'id': question.pk,
            'question': question.question,
            'hint3': question.hint3,
            'hint2': question.hint2,
            'hint1': question.hint1,
            'answer': question.answer,
            'color': Question.COLORS[question.color]
        }
        return render(request, 'idunno/question_edit.html', context)


def question(request, question_id):
    question = Question.objects.get(pk=question_id)
    context = {
        'id': question.pk,
        'question': question.question,
        'hint3': question.hint3,
        'hint2': question.hint2,
        'hint1': question.hint1,
        'answer': question.answer,
        'color': Question.COLORS[question.color]
    }
    return render(request, 'idunno/question.html', context)


def game(request, query):
    try:
        query = int(query)
        question = Question.objects.get(pk=query)
    except ValueError:
        color = None if query == '?' else query
        question = Question.get_random_question(color)

    context = {
        'index': True,
        'id': question.pk,
        'question': question.question,
        'hint3': question.hint3,
        'hint2': question.hint2,
        'hint1': question.hint1,
        'answer': question.answer,
        'color': Question.COLORS[question.color]
    }
    return render(request, 'idunno/game.html', context)


def search(request, query):
    context = {}
    questions = Question.objects.filter(
        Q(question__icontains=query) |
        Q(hint3__icontains=query) |
        Q(hint2__icontains=query) |
        Q(hint1__icontains=query) |
        Q(answer__icontains=query)
    )
    context["query"] = query
    context["questions"] = questions
    # print(questions)
    return render(request, "idunno/list.html", context=context)

idunno/templates/idunno/card.html
{% load static %}

<div class="idunno-card">
    <table>
        <tr>
            <td colspan="2" class="w-50">
                {% if not index %}
                    <h3 style="float:left" class="idunno-card-title">{{ question }}</h3>
                {% else %}
                    <a href="{% url "question" id %}"><h3 style="float:left"
                                                          class="idunno-card-title">{{ question }}</h3></a>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td class="symb">
                <object data="{% static "img/hint3.svg" %}" type="image/svg+xml" class="idunno-symb hint"></object>
            </td>
            <td class="idunno-hidden">{{ hint3 }}</td>
        </tr>
        <tr>
            <td class="symb">
                <object data="{% static "img/hint2.svg" %}" type="image/svg+xml" class="idunno-symb hint"></object>
            </td>
            <td class="idunno-hidden">{{ hint2 }}</td>
        </tr>
        <tr>
            <td class="symb">
                <object data="{% static "img/hint1.svg" %}" type="image/svg+xml" class="idunno-symb hint"></object>
            </td>
            <td class="idunno-hidden">{{ hint1 }}</td>
        </tr>
        <tr>
            <td>
                <object data="{% static "img/star.svg" %}" type="image/svg+xml" class="idunno-symb ans"></object>
            </td>
            <td class="idunno-hidden" style="font-weight: bold">{{ answer }}</td>
        </tr>
    </table>
</div>

<style>
    .idunno-card tr {
        height: 6em;
    }

    .idunno-card symb td {
        width: 6em;
    }

    .idunno-symb {
        margin-right: 2em;
        float: left;
        height: 3em;
        width: 3em;
    }

    .idunno-symb.ans {
        height: 1em;
        width: 1em;
        margin-left: 1.5em;
    }
</style>

idunno/templates/idunno/card_blank.html
{% load static %}

<style>
    .idunno-card tr{
        height: 3em;
    }
    .idunno-color td {
        text-align: center;
    }
    .idunno-symb {
        text-align: center;
    }
    .idunno-question .idunno-symb {
        font-size:2em;
    }

    .idunno-hint .idunno-symb {
        height:3em;
        width:3em;
    }
    .idunno-answer .idunno-symb {
        height: 1.5em;
        width: 1.5em;
    }

    .idunno-card-buttons {
        text-align: center;
    }
    .idunno-card-buttons button {
        width:80px;
    }

</style>

<div class="idunno-card">
    <form class="form-horizontal post-form" method="POST">
        {% csrf_token %}
        <table class="table-borderless w-100 my-3">
            <tr class="idunno-color">
                <td colspan="2">
                    <select id="select_color" class="selectpicker form-control btn-default w-25 d-inline " name="color" required="" id="id_color">
                        <option value="B" style="color:#009ce5">&#9679;</option>
                        <option value="G" style="color:#33ac2d">&#9679;</option>
                        <option value="R" style="color:#e50c07">&#9679;</option>
                        <option value="Y" style="color:#fdc500">&#9679;</option>
                    </select>
                </td>
            </tr>
            <tr class="idunno-question">
                <td class="idunno-symb">
                    <i class="fas fa-question"></i>
                </td>
                <td class="idunno-text">
                    <textarea name="question" class="form-control" required="" id="id_question"></textarea>
                </td>
            </tr>
            <tr class="idunno-hint">
                <td class="idunno-symb">
                    <object data="{% static "img/hint3.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
                </td>
                <td class="idunno-text">
                    <textarea name="hint3" class="form-control" required="" id="id_hint3"></textarea>
                </td>
            </tr>
            <tr class="idunno-hint">
                <td class="idunno-symb">
                    <object data="{% static "img/hint2.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
                </td>
                <td class="idunno-text">
                    <textarea name="hint2" class="form-control" required="" id="id_hint2"></textarea>
                </td>
            </tr>
            <tr class="idunno-hint">
                <td class="idunno-symb">
                    <object data="{% static "img/hint1.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
                </td>
                <td class="idunno-text">
                    <textarea name="hint1" class="form-control" required="" id="id_hint1"></textarea>
                </td>
            </tr>
            <tr class="idunno-answer">
                <td class="idunno-symb">
                    <object data="{% static "img/star.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
                </td>
                <td class="idunno-text">
                    <textarea name="answer" class="form-control" required="" id="id_answer"></textarea>
                </td>
            </tr>
            <tr class="idunno-card-buttons">
                <td colspan="2">
                    <button type="submit" class="btn btn-primary" ><i class="fa fa-save"></i></button>
                    <button type="reset" class="btn btn-secondary"><i class="fa fa-ban"></i></button>
                </td>
            </tr>
        </table>
    </form>
</div>

<script>
    function change_symbol_color(color){
        let symbs = document.querySelectorAll(".idunno-symb object");

        for (symb of symbs) {
            let svg = symb.contentDocument;
            let pts = svg.getElementsByTagName('circle');
            for (pt of pts){
                pt.style.fill = color;
                pt.style.stroke = 'none';
            }
         }
    }

    let sc= document.getElementById('select_color');
    sc.addEventListener("change",function() {
        let sel_col = sc.options[sc.selectedIndex].style.color;
        sc.style.color = sel_col;
        change_symbol_color(sel_col);
    });

</script>

idunno/templates/idunno/card_edit.html
{% load static %}

<style>
    .idunno-card tr {
        height: 3em;
        margin-top: 1em;
        margin-bottom: 1em;
    }

    .idunno-color td {
        text-align: center;
    }

    .idunno-symb {
        text-align: center;
        margin-left: 2em;
        margin-right: 2em;
    }

    .idunno-question .idunno-symb {
        font-size: 2em;
    }

    .idunno-hint .idunno-symb {
        height: 3em;
        width: 3em;
    }

    .idunno-answer .idunno-symb {
        height: 1.5em;
        width: 1.5em;
    }

    .idunno-card-buttons {
        text-align: center;
    }

    .idunno-card-buttons button {
        width: 80px;
    }

    .idunno-card .idunno-edit {
        height: 2em;
        width: 2em;
        color: #007bff;
    }

    .idunno-card .idunno-edit:hover {
        transition-duration: 0.2s;
        font-size: large;
        color: #000000;
    }

</style>

<div class="idunno-card">
    <table class="table-borderless w-100 my-3">
        <tr class="idunno-color" data-property="color">
            <td colspan="3">
                <select id="select_color" class="selectpicker form-control btn-default w-25 d-inline " name="color"
                        required="" id="id_color">
                    <option value="B" style="color:#009ce5">&#9679;</option>
                    <option value="G" style="color:#33ac2d">&#9679;</option>
                    <option value="R" style="color:#e50c07">&#9679;</option>
                    <option value="Y" style="color:#fdc500">&#9679;</option>
                </select>
            </td>
        </tr>
        <tr class="idunno-question modalable" data-property="question">
            <td class="idunno-symb">
                <i class="fas fa-question"></i>
            </td>
            <td class="idunno-text">
                <h3>{{ question }}</h3>
            </td>
            <td class="idunno-edit">
            </td>
        </tr>
        <tr class="idunno-hint modalable" data-property="hint3">
            <td class="idunno-symb">
                <object data="{% static "img/hint3.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
            </td>
            <td class="idunno-text">
                {{ hint3 }}
            </td>
            <td class="idunno-edit">
            </td>
        </tr>
        <tr class="idunno-hint modalable" data-property="hint2">
            <td class="idunno-symb">
                <object data="{% static "img/hint2.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
            </td>
            <td class="idunno-text">
                {{ hint2 }}
            </td>
            <td class="idunno-edit">
            </td>
        </tr>
        <tr class="idunno-hint modalable" data-property="hint1">
            <td class="idunno-symb">
                <object data="{% static "img/hint1.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
            </td>
            <td class="idunno-text">
                {{ hint1 }}
            </td>
            <td class="idunno-edit">
            </td>
        </tr>
        <tr class="idunno-answer modalable" data-property="answer">
            <td class="idunno-symb">
                <object data="{% static "img/star.svg" %}" type="image/svg+xml" class="idunno-symb"></object>
            </td>
            <td class="idunno-text">
                {{ answer }}
            </td>
            <td class="idunno-edit">
            </td>
        </tr>
        <tr class="idunno-card-buttons">
            <td colspan="3">
                <button type="submit" class="btn btn-secondary"><i class="fa fa-save"></i></button>
                <a href="{% url "question" id %}">
                    <button type="reset" class="btn btn-default"><i class="fa fa-ban"></i></button>
                </a>
            </td>
        </tr>
    </table>
</div>

<script>
    // Changes the color of the hint symbols to specified color
    function change_symbol_color(color) {
        let symbs = document.querySelectorAll(".idunno-symb object");

        for (symb of symbs) {
            let svg = symb.contentDocument;
            let pts = svg.getElementsByTagName('circle');
            for (pt of pts) {
                pt.style.fill = color;
                pt.style.stroke = 'none';
            }
        }
    }

    window.onload = function () {
        change_symbol_color('{{ color }}');
    };
    // Event listener for the select color, that changes the hint symbols accordingly
    let sc = document.getElementById('select_color');
    sc.addEventListener("change", function () {
        let sel_col = sc.options[sc.selectedIndex].style.color;
        sc.style.color = sel_col;
        change_symbol_color(sel_col);
    });

    ///////////////////////////////////////////////////////////

    // Event listeners for displaying the edit pencil in the rows
    let rows = document.querySelectorAll(".modalable");
    for (row of rows) {
        row.addEventListener('mouseenter', function (e) {
            let trigger_row = e.target;
            let edit_cell = trigger_row.querySelector('.idunno-edit');
            let edit_icon_node = document.createElement('i');
            let property = trigger_row.getAttribute('data-property');
            edit_icon_node.className = 'fas fa-pencil-alt';
            edit_icon_node.setAttribute('data-toggle', 'modal');
            edit_icon_node.setAttribute('data-target', '#valueModal');
            edit_icon_node.setAttribute('data-property', property);
            edit_icon_node.setAttribute('data-hover', true);
            edit_cell.appendChild(edit_icon_node);
        });
        row.addEventListener('mouseleave', function (e) {
            let trigger_row = e.target;
            let edit_icon_node = trigger_row.querySelector('[data-hover=true]');
            edit_icon_node.remove();
        });
    }

    // sets the modal up according to the row that is going to be edited
    $('#valueModal').on('show.bs.modal',
        function (e) {
            let property = $(e.relatedTarget).data('property');
            let prop_val = document.querySelector('[data-property=' + property + '] .idunno-text').innerHTML.trim();
            let modal = $(e.target);

            let icon = null;

            if (property == 'question') {
                icon = document.createElement('i');
                icon.className = 'fas fa-question';
            } else {
                icon = $("[data-property=" + property + "] object ")[0];
                icon = icon.cloneNode(true);
            }
            let label = document.querySelector('.modal-body label');
            label.appendChild(icon);
            modal.find('#new_value').val(prop_val);
            modal.find('#new_value').attr('data-property', property);
            $('.idunno-card-buttons [type=submit]').attr('id', 'submit');
            $('.idunno-card-buttons [type=submit]').attr('class', 'btn btn-primary');
            $('.idunno-card-buttons [type=submit]').on('click', send_to_server);

        });

    // removes the setup from the modal, so that it can be changed, when editing another property
    $('#valueModal').on('hide.bs.modal',
        function (e) {
            let label = document.querySelector('.modal-body label');
            label.innerHTML = "";
        });


    $('#modal_set_button').on('click',
        function (e) {
            let modal = $('#valueModal');
            let property = modal.find('#new_value').attr('data-property');
            let new_prop_val = modal.find('#new_value').val();
            $('[data-property=' + property + '] .idunno-text').text(new_prop_val);
        });


    function send_to_server() {
        let data = {
            'color': $('.idunno-color select').val(),
            'question': $('.idunno-question .idunno-text').text().trim(),
            'hint3': $('[data-property=hint3] .idunno-text').text().trim(),
            'hint2': $('[data-property=hint2] .idunno-text').text().trim(),
            'hint1': $('[data-property=hint1] .idunno-text').text().trim(),
            'answer': $('.idunno-answer .idunno-text').text().trim(),
        };
        data = JSON.stringify(data);
        console.log(data);
        let token = '{{ csrf_token }}';

        $.ajax({
            headers: {"X-CSRFToken": token},
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            url: "{% url "edit" id %}",
            data: data,
            success: function (result) {
                //show the alert
                console.log(result);
                $('#success_alert').toggleClass('fade');
                $('#success_alert').toggleClass('d-none');
                $('#close_success_button').on('click', function () {
                    //hide the alert
                    $('#success_alert').toggleClass('hide');
                });
            }
        })
    }
</script>

idunno/templates/idunno/ext.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">#}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<!-- Custom externals  -->
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

idunno/templates/idunno/footer.html
<footer class="container-fluid text-center mt-auto footer">
   iDunno App by Bierli: <a href="mailto:david.rejchrt@tuwien.ac.at"><i class="fa fa-envelope"></i></a><br>
   Feel free to contribute: <a href="https://github.com/drejchrt/iDunno"><i class="fab fa-github"></i></a>

</footer>

<style>
    html {
        position: relative;
        min-height: 100%;
    }

    body {
        margin-bottom: 60px; /* Margin bottom by footer height */
    }

    footer {
        color: #FFFFFF;
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 60px; /* Set the fixed height of the footer here */
        {#line-height: 60px; /* Vertically center the text there */#}
        background-color: #007bff;
    }

    footer a {
        color: #FFFFFF;
    }

    footer a:hover {
        color: #000000;
    }
</style>

idunno/templates/idunno/game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>iDunno</title>

    {% include "idunno/ext.html" %}
    <style>
        .main, .control {
            text-align: center;
        }

        .btn img {
            height: 1.5em;
            width: 1.5em;
        }

        .idunno-hidden {
            visibility: hidden;
        }

    </style>
</head>
<body>

{% include "idunno/navbar.html" %}

<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-3 d-none d-md-block sidebar">
            &nbsp
        </div>
        <div class="col-md-6 col-sm-12 text-left main">
            {% include "idunno/card.html" %}
        </div>
        <div class="col-md-3 d-none d-md-block sidebar">
            &nbsp
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 d-none d-md-block sidebar">
            &nbsp
        </div>
        <div class="col-md-6 col-sm-12 text-center main control">
            <div class="btn btn-success w-25 m-3" id="uncover_next">
                <img src="{% static "img/hint3.svg" %}"></img>
            </div>
            <div class="btn-group dropup w-25 m-3">
                <div type="button" class="btn btn-secondary dropdown-toggle w-100" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                    <img src="{% static "img/colors.svg" %}">
                </div>
                <div class="dropdown-menu text-center">
                    <a class="dropdown-item" href="{% url "game" 'B' %}" style="color:#009ce5">
                        <i class="fa fa-circle" aria-hidden="true"></i>
                    </a>
                    <a class="dropdown-item" href="{% url "game" 'G' %}" style="color:#33ac2d">
                        <i class="fa fa-circle" aria-hidden="true"></i>
                    </a>
                    <a class="dropdown-item" href="{% url "game" 'R' %}" style="color:#e50c07">
                        <i class="fa fa-circle" aria-hidden="true"></i>
                    </a>
                    <a class="dropdown-item" href="{% url "game" 'Y' %}" style="color:#fdc500">
                        <i class="fa fa-circle" aria-hidden="true"></i>
                    </a>
                </div>
            </div>

        </div>
        <div class="col-md-3 d-none d-md-block sidebar">
            &nbsp
        </div>
    </div>
    {% include "idunno/footer.html" %}
</div>
<script>
    function change_symbol_color(color) {
        let symbs = document.getElementsByClassName("idunno-symb");

        for (symb of symbs) {
            let svg = symb.contentDocument;
            let pts = svg.getElementsByTagName('circle');
            for (pt of pts) {
                pt.style.fill = color;
                pt.style.stroke = 'none';
            }
        }
    }

    window.onload = function () {
        change_symbol_color('{{ color }}');
        document.querySelector('#uncover_next').addEventListener('click', uncover)
    };

    let _HINTS = 3;

    function uncover() {
        let item = $('.idunno-hidden').first();
        item.toggleClass('idunno-hidden');
        let icon_url = null
        switch (_HINTS - 1) {
            case 2: {
                icon_url = '{% static "img/hint2.svg" %}';
                break;
            }
            case 1: {
                icon_url = '{% static "img/hint1.svg" %}';
                break;
            }
            default: {
                icon_url = '{% static "img/star.svg" %}';
                break;
            }
        }
        $('#uncover_next img').attr('src', icon_url);

        if (_HINTS >= 0) {
            _HINTS--;
        } else {
            alert('All hints and answer shown')
        }
    }


</script>
</body>
</html>

idunno/templates/idunno/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>iDunno</title>

    {% include "idunno/ext.html" %}

</head>
<body>

{% include "idunno/navbar.html" %}

<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-3 d-none d-md-block sidebar">
           &nbsp
        </div>
        <div class="col-md-6 col-sm-12 text-left main">
            {% include "idunno/card.html" %}
        </div>
        <div class="col-md-3 d-none d-md-block sidebar">
            &nbsp
        </div>
    </div>
    {% include "idunno/footer.html" %}
</div>
<script>
    function change_symbol_color(color){
        let symbs = document.getElementsByClassName("idunno-symb");

        for (symb of symbs) {
            let svg = symb.contentDocument;
            let pts = svg.getElementsByTagName('circle');
            for (pt of pts){
                pt.style.fill = color;
                pt.style.stroke = 'none';
            }
         }
    }
    window.onload = function() {
        change_symbol_color('{{ color }}');
    };

</script>
</body>
</html>

idunno/templates/idunno/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a href="{% url "index" %}"><h5 class="navbar-brand">iDunno</h5></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a href="{% url "index" %}"><i class="fa fa-home"></i></a></li>
            <li class="nav-item"><a href="{% url "list" sort_attr='id' %}"><i class="fa fa-list"></i></a></li>
            <li class="nav-item"><a href="{% url "add_question" %}"><i class="fa fa-plus"></i></a></li>
            <li class="nav-item"><a href="{% url "game" '?' %}"><i class="fas fa-dice"></i></a></li>
        </ul>
        <div class="form-inline">
            <input id="searchbar" class="form-control mr-sm-2 w-100" type="search" placeholder="?" aria-label="Search">
            <div id="submit_btn" class="btn btn-default my-2 my-sm-0">
                <i class="fa fa-search" aria-hidden="true"></i>
            </div>
        </div>
    </div>
</nav>

<style>
    #submit_btn {
        position: absolute;
        right: 1em;
        display: inline;
        z-index: 2;
        color: #007bff;
    }

    .navbar {
        text-align: center;
    }

    .navbar .nav-item {
        margin-left: 1em;
        margin-right: 1em;
        font-size: 2em;

    }

    .navbar a:hover {
        color: #FFFFFF;
    }
</style>

<script>
    console.log();

    $('#submit_btn').on('click', function () {
        let query = $('#searchbar').val();
        let url = "{% url "search" "0000" %}";
        console.log(url);
        url = url.replace('0000', query);
        console.log(url);
        window.location = url;
    })
</script>

idunno/templates/idunno/navbar_search_res.html
{% if questions %}
    {% for q in questions %}
        <a href="{% url "question" q.id %}">{{ q.question }} | {{ q.answer }}</a><br>
    {% endfor %}
{% endif %}

idunno/templates/idunno/newQuestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>iDunno | New Question</title>

    {% include "idunno/ext.html" %}

{#<style>#}
{#        .idunno-card tr {#}
{#            height: 6em;#}
{#        }#}
{##}
{#        .idunno-card symb td {#}
{#            width: 6em;#}
{#        }#}
{##}
{#        .idunno-symb {#}
{#            margin-left: 2em;#}
{#            text-align: center;#}
{#            float: left;#}
{#            height: 3em;#}
{#            width: 3em;#}
{#        }#}
{##}
{#        .idunno-ans {#}
{#            height: 1em;#}
{#            width: 1em;#}
{#            margin-left: 3em;#}
{#        }#}
{#    </style>#}
</head>
<body>
{% include "idunno/navbar.html" %}

<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-md-3 d-none d-md-block sidebar">
        </div>
        <div class="col-md-6 col-sm-12 text-left main">
            {% include "idunno/card_blank.html" %}
        </div>
        <div class="col-md-3 d-none d-md-block sidebar">
        </div>
    </div>
</div>

{% include "idunno/footer.html" %}

{#{% block content %}#}
{#    <h2>New Question</h2>#}
{#    <form method="POST" class="post-form">{% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Save</button>#}
{#    </form>#}
{#{% endblock %}#}


</body>
</html>